/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Menu generowane automatycznie na podstawie struktury folderu docs/
  // i pola sidebar_position w nagłówku (front matter) każdego pliku .md
  cwiczeniaSidebar: [{ type: 'autogenerated', dirName: '.' }],
};

module.exports = sidebars;
